server:
  port: 8200
  servlet:
    context-path: /diary
mybatis:
  mapper-locations: classpath:/mapper/*.xml
spring:
  mvc:
    servlet:
      load-on-startup: 1

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: dingjinhui
    password: Zwx0907.
    url: jdbc:mysql://localhost:3306/diary?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true

logging:
  level:
    root: info
    com.ding.diary: debug
  info-path: /ftp/diary/logs/info.%d.log
  error-path: /ftp/diary/logs/error.%d.log